# Generated by Django 6.0.2 on 2026-02-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(choices=[('llama 3', 'llama3'), ('gemma 3', 'gemma3')], default='llama 3', max_length=50),
        ),
    ]
