# Generated by Django 4.2.27 on 2026-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0003_alter_llmconfig_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(choices=[('llama3', 'Llama 3'), ('gemma3', 'Gemma 3')], default='llama3', max_length=50),
        ),
    ]
